apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: interna
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      nodeSelector:
        zona: interna          # Redis solo en la red interna
      containers:
        - name: redis
          image: redis:7
          ports:
            - containerPort: 6379
          command: ["redis-server"]
